name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        channel: 
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{matrix.channel}}

      - name: Install dependencies
        run: flutter pub get

      - name: Run code formatting check
        run: flutter format --set-exit-if-changed .

      - name: Run tests
        run: flutter test

  ios-build:
    strategy:
      matrix:
        channel:
          - stable
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{matrix.channel}}

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: flutter build ipa --release

      - name: Archive the iOS app
        uses: actions/upload-artifact@v2
        with:
          name: app.ipa
          path: build/ios/ipa/*.ipa
